# This viminfo file was generated by Vim 9.0.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Command Line History (newest to oldest):
:q!
|2,0,1783493195,,"q!"

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):

# Debug Line History (newest to oldest):

# Registers:

# File marks:
'0  1  0  ~/Projects/workspace-eclipse-2024/circuitjs1/src/com/lushprojects/circuitjs1/public/locale_csx.txt
|4,48,1,0,1783493195,"~/Projects/workspace-eclipse-2024/circuitjs1/src/com/lushprojects/circuitjs1/public/locale_csx.txt"

# Jumplist (newest first):
-'  1  0  ~/Projects/workspace-eclipse-2024/circuitjs1/src/com/lushprojects/circuitjs1/public/locale_csx.txt
|4,39,1,0,1783493195,"~/Projects/workspace-eclipse-2024/circuitjs1/src/com/lushprojects/circuitjs1/public/locale_csx.txt"

# History of marks within files (newest to oldest):

> ~/Projects/workspace-eclipse-2024/circuitjs1/src/com/lushprojects/circuitjs1/public/locale_csx.txt
	*	1783493193	0
	"	1	0
